name: assignment3
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Log Start Time
        run: echo -e "$(date -Iminutes)" > /tmp/log.txt

      - name: Submitters
        run: echo -e "Ayal Galanti, Hila Ashkenazy, Tomer Sapir" >> /tmp/log.txt

      - name: Print Log File Contents
        run: cat /tmp/log.txt

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Export Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./books
          tags: books:latest, ${{ secrets.DOCKER_USERNAME }}/books:latest
          outputs: type=docker,dest=/tmp/image.tar

      - name: Handle Build Failure
        if: failure()
        run: echo -e "image not able to be built" >> /tmp/log.txt

      - name: Handle Build Success
        if: success()
        run: echo -e "image successfully built" >> /tmp/log.txt

      - name: Print Final Log File Contents
        run: cat /tmp/log.txt

      - name: Upload Log File
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: log
          path: /tmp/log.txt

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: books
          path: /tmp/image.tar

      - name: Start Docker Container
        if: success()
        run: docker-compose up -d

      - name: Wait for Container to Start
        if: success()
        run: sleep 10

      - name: Check Container Status
        if: success()
        run: |
          if docker ps --filter "name=books" --filter "status=running" | grep books; then
            echo "Container up and running" >> /tmp/log.txt
          else
            echo "Container failed to run" >> /tmp/log.txt
          fi

      - name: Print Final Log File After Container Check
        if: success()
        run: cat /tmp/log.txt
